name: unit

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: [ "ubuntu-22.04", "ubuntu-24.04", "ubuntu-latest" ]
        python-version: [ "3.10", "3.11", "3.12" ]
    runs-on: ${{ matrix.ubuntu-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        lfs: 'true'
    - name: Setup python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt setuptools
        sudo sysctl kernel.dmesg_restrict=0
    - name: Test "list"
      run: ./vaapi-fits list
    - name: Test "self"
      run: ./vaapi-fits run --pl NA --device /dev/null -vv --parallel-metrics --call-timeout 10 --ctapr 0 test/self
